### ISSUE TITLE
`pytest.approx` does not raise in mixed data type nested structures

### ISSUE THREAD

**Issue by jkittner** [pytest-dev/pytest#10210]
### description

when using `pytest.approx` on nested data structures I'd expect it to raise an exception also for mixed data type containers like a `tuple` in a `list`. So far it only works for the same data types e.g. lists in lists, tuples in tuples.
For mixed data structures it incorrectly returns `False`, even though they should match which is a little misleading (also see below).

### output of `pip list`
```console
(venv) kittnjdr@ububox:~/workspace/pytest$ pip list
Package    Version                 Editable project location
---------- ----------------------- -------------------------------
attrs      22.1.0
iniconfig  1.1.1
packaging  21.3
pip        22.1.2
pluggy     1.0.0
py         1.11.0
pyparsing  3.0.9
pytest     7.2.0.dev232+gcc0092b9d /home/kittnjdr/workspace/pytest
setuptools 63.2.0
tomli      2.0.1
wheel      0.37.1
```
### versions
- pytest: main branch
- OS: ubuntu 22.04
### minimal reproduction
```pycon
>>> import pytest
>>> [(1.0001,)] == pytest.approx([(1,)], rel=1e-2)
False
>>> ({1.0001},) == pytest.approx(({1},), rel=1e-2)
False
>>> ({"key": 1.0001},) == pytest.approx(({"key": 1},), rel=1e-2)
False
>>> (1.0001,) == pytest.approx((1,), rel=1e-2)
True
>>> ((1.0001,),) == pytest.approx(((1,),), rel=1e-2)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/kittnjdr/workspace/pytest/src/_pytest/python_api.py", line 744, in approx
    return cls(expected, rel, abs, nan_ok)
  File "/home/kittnjdr/workspace/pytest/src/_pytest/python_api.py", line 86, in __init__
    self._check_type()
  File "/home/kittnjdr/workspace/pytest/src/_pytest/python_api.py", line 381, in _check_type
    raise TypeError(msg.format(x, index, pprint.pformat(self.expected)))
TypeError: pytest.approx() does not support nested data structures: (1,) at index 0
  full sequence: ((1,),)
```
however, it works fine if both are exactly the same, but here I'd also expect an exception instead of a result (which is correct, but maybe unintentional)
```pycon
>>> [(1.0,)] == pytest.approx([(1.0,)])
True
```
### test cases

These test cases fail, but should pass with the potential bug fixed.

```diff
diff --git a/testing/python/approx.py b/testing/python/approx.py
index 6acb466ff..31dd4638b 100644
--- a/testing/python/approx.py
+++ b/testing/python/approx.py
@@ -781,6 +781,10 @@ class TestApprox:
         "x, name",
         [
             pytest.param([[1]], "data structures", id="nested-list"),
+            pytest.param([(1,)], "data structures", id="nested-list-tuple"),
+            pytest.param([{1}], "data structures", id="nested-list-set"),
+            pytest.param([{"key": 1}], "data structures", id="nested-list-dict"),
             pytest.param({"key": {"key": 1}}, "dictionaries", id="nested-dict"),
         ],
     )
```

**Comment by ptkenny** [comment]
I'm gonna try taking a look at this one, will update if I get stuck(this is my first issue in this project).

**Comment by theendlessriver13** [comment]
This might be a tricky one, since some fundamental changes might be necessary.
Ronny wrote:
> I agree, feature creep happened, problem is that with a surround for the collection, the errors can't be done sanely

> We just finished some early design discussions about that last month and it will take a while to manifest

**Comment by ptkenny** [comment]
I released the PR anyway, if anything it might be a decent temporary fix.

**Comment by danielgafni** [comment]
Hey guys! Not sure what is the state of this issue, but the bug is still there: 

```python
>>> pytest.approx([{"a": 0.1}], rel=1e-1) == [{"a": 0.11}]
False
>>> pytest.approx(0.1, rel=1e-1) == 0.11
True
```

Pytest version is `7.2.0`

**Comment by onk3sh** [comment]
Still reproduces on `main` (10.0.0.dev):

```python
>>> import pytest
>>> [{"a": 0.1 + 1e-9}] == pytest.approx([{"a": 0.1}])     # well inside default tolerance
False
>>> [{"a": 0.1}] == pytest.approx([{"a": 0.1}])            # only exact equality passes
True
>>> [[0.1 + 1e-9]] == pytest.approx([[0.1]])               # same shape, same-type nesting
TypeError: pytest.approx() does not support nested data structures: [0.1] at index 0
```

The cause is that both nesting guards compare against the *parent's* type:

- `src/_pytest/approx.py:263` — `ApproxMapping.__init__`: `if isinstance(value, type(expected)):`
- `src/_pytest/approx.py:361` — `ApproxSequenceLike.__init__`: `if isinstance(x, type(expected)):`

So a nested container is only detected when it happens to be the same type as the one holding it. Any other combination — dict in a list, list in a dict, tuple in a list, set in a tuple — slips through and is then compared with `==` as a leaf value, which is exact. The tolerance is silently ignored: the result is `False` for anything but exact equality, and `True` when the values happen to match exactly.

Passing `rel=` explicitly gives a third behaviour, a misleading error from a different layer:

```python
>>> [{"a": 0.11}] == pytest.approx([{"a": 0.1}], rel=1e-1)
TypeError: expected value must support abs(...) when relative tolerance is used, got dict
```

Fix is to ask whether the value is a container at all rather than whether it matches the parent's type, keeping `str`/`bytes`/`bytearray` as leaves since those already compare exactly by design (`test_nonnumeric_okay_if_equal` covers them).

@Zac-HD, you closed #10215 with "we'd be delighted to accept a fresh version of this patch" — I've taken you up on that. The 2022 patch only touched the sequence side, so `approx({"a": [1.0]})` would still have been silently wrong; this one fixes both. PR incoming with regression tests for every cross-kind combination and a changelog entry.
