### ISSUE TITLE
pytester plugin is no longer rewritten

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [pytest-dev/pytest#1920]
```
/home/ronny/Projects/pytest-dev/pytest/testing/python/metafunc.py:1395: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <_pytest.pytester.HookRecorder instance at 0x7f85e2d9ea70>, passed = 1, skipped = 0, failed = 0

    def assertoutcome(self, passed=0, skipped=0, failed=0):
        realpassed, realskipped, realfailed = self.listoutcomes()
>       assert passed == len(realpassed)
E       AssertionError

/home/ronny/Projects/pytest-dev/pytest/_pytest/pytester.py:312: AssertionError
---------------------------------------------------------------------------------------------- Captured stdout call -----------------------------------------------------------------------------------------------
============================= test session starts ==============================
platform linux2 -- Python 2.7.12, pytest-3.1.0.dev0, py-1.4.31, pluggy-0.3.1
rootdir: /tmp/pytest-of-ronny/pytest-124/testdir/test_parametrize_marked_value1, inifile: 
plugins: hypothesis-3.4.2
collected 2 items

test_parametrize_marked_value.py XX

```

**Comment by RonnyPfannschmidt** [comment]
@nicoddemus isnt that one fixed by the handling of pytest_plugins you added ?

**Comment by nicoddemus** [comment]
Strange, it is still not working as of `3.0.5`:

```python
pytest_plugins = ['pytester']


def test(testdir):
    testdir.makepyfile('def test(): assert 0')
    r = testdir.inline_run()
    r.assertoutcome(passed=1)
```

And doesn't print any warnings either...
