### ISSUE TITLE
ImportError: cannot import name UnexpectedException

### ISSUE THREAD

**Issue by amarao** [pytest-dev/pytest#2432]
Pytest version: 3.0.6-1

My project has tests in the 'doctest' folder (they test if examples from docs are still valid).
If there is such folder name in the project,  py.test fails on failed tests with --pdb option:
```
    def test_test():
>       raise Exception
E       Exception

test.py:2: Exception
```

```
Traceback (most recent call last):
  File "/usr/bin/py.test", line 11, in <module>
    load_entry_point('pytest==3.0.6', 'console_scripts', 'pytest')()
  File "/usr/lib/python2.7/dist-packages/_pytest/config.py", line 57, in main
    return config.hook.pytest_cmdline_main(config=config)
  File "/usr/lib/python2.7/dist-packages/_pytest/vendored_packages/pluggy.py", line 745, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "/usr/lib/python2.7/dist-packages/_pytest/vendored_packages/pluggy.py", line 339, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/usr/lib/python2.7/dist-packages/_pytest/vendored_packages/pluggy.py", line 334, in <lambda>
    _MultiCall(methods, kwargs, hook.spec_opts).execute()
  File "/usr/lib/python2.7/dist-packages/_pytest/vendored_packages/pluggy.py", line 614, in execute
    res = hook_impl.function(*args)
  File "/usr/lib/python2.7/dist-packages/_pytest/main.py", line 127, in pytest_cmdline_main
    return wrap_session(config, _main)
  File "/usr/lib/python2.7/dist-packages/_pytest/main.py", line 111, in wrap_session
    config.notify_exception(excinfo, config.option)
  File "/usr/lib/python2.7/dist-packages/_pytest/config.py", line 936, in notify_exception
    excinfo=excinfo)
  File "/usr/lib/python2.7/dist-packages/_pytest/vendored_packages/pluggy.py", line 745, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "/usr/lib/python2.7/dist-packages/_pytest/vendored_packages/pluggy.py", line 339, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/usr/lib/python2.7/dist-packages/_pytest/vendored_packages/pluggy.py", line 334, in <lambda>
    _MultiCall(methods, kwargs, hook.spec_opts).execute()
  File "/usr/lib/python2.7/dist-packages/_pytest/vendored_packages/pluggy.py", line 614, in execute
    res = hook_impl.function(*args)
  File "/usr/lib/python2.7/dist-packages/_pytest/debugging.py", line 79, in pytest_internalerror
    tb = _postmortem_traceback(excinfo)
  File "/usr/lib/python2.7/dist-packages/_pytest/debugging.py", line 101, in _postmortem_traceback
    from doctest import UnexpectedException
ImportError: cannot import name UnexpectedException
```

**Comment by RonnyPfannschmidt** [comment]
do you have a `__init__.py` in the doctest folder?

if yes you shadow a python library of the stdlib and deliberately broke the world

**Comment by amarao** [comment]
Yes, it does. But should py.test relies on project-local libraries for own needs?

**Comment by RonnyPfannschmidt** [comment]
@amarao no, what you do is hide the python standard library from pytest - so pytest finds your code instead of the doctest library that belongs to python and breaks, because yours works differently

so this is not a issue in pytest, but an issue in your codebase

**Comment by nicoddemus** [comment]
@amarao, this is fixed in pytest 3.1.0 because we added a `__future__.absolute_import` statement to our internal files. Could you please try it?

**Comment by amarao** [comment]
Unfortunately with 3.1 it's the same, UnexpectedException.

I solved my problem with rename of doctest to doctests, but the problem is still exist: I someone used name of python module for own module (It may be the case if python standard module with same name is not used in app), than py.test may misbehave with this application.

For my case it is really strange that it happens only if `--pdb` key was used.

**Comment by nicoddemus** [comment]
This is strange indeed. Could you provide a reproducible example?

**Comment by amarao** [comment]
```
mkdir /tmp/foo
cd /tmp/foo
virtualenv .foo
source  .foo/bin/activate
pip install pytest
mkdir doctest
touch doctest/__init__.py
echo -e 'def test_raise():\n\traise Exception()' > doctest/test.py
py.test doctest/test.py --pdb
```

**Comment by RonnyPfannschmidt** [comment]
@amarao that is deliberate shadowing of a stdlib module, its python default behavior to break exactly the way you see it break

**Comment by nicoddemus** [comment]
Yep; I asked for an example mostly because your layout directory was something like `my_app.doctest`, which would be curious as why it was failing. But `doctest` as a root folder there is really nothing pytest can do. 

You can check this by doing:

```
python -c "from doctest import UnexpectedException"
```

In that same directory: Python will import your `doctest` module instead of the standard `doctest` module.
