### ISSUE TITLE
Setting a fixture scope of "package" will not teardown the fixture

### ISSUE THREAD

**Issue by hayleyday** [pytest-dev/pytest#3796]
I am using Windows 10, Python 3.6, and pytest 3.7.1 or 3.7.0 (tested with both).

Here are the libraries I have installed:
atomicwrites   1.1.5
attrs          18.1.0
colorama       0.3.9
more-itertools 4.3.0
pip            9.0.3
pluggy         0.7.1
psutil         5.4.6
py             1.5.4
pyserial       3.4
pytest         3.7.1
setuptools     40.0.0
six            1.11.0
websocket-server 0.4

It appears as though when a fixture is setup with a scope of package, the teardown code does not execute. 

Simple example:

```python
@pytest.fixture(scope="package")
def example():
   setup_code()
   yield something
   teardown_code()
```

For this example, "teardown_code()" is never executed for me.

**Comment by nicoddemus** [comment]
Hi @hayleyday,

Thanks for reporting it. I could not reproduce it with this example though:

```python
import pytest

@pytest.fixture(scope='package')
def fix():
    print('setup')
    yield 1
    print('teardown')

def test(fix):
    assert fix == 1
```

```
λ pytest -s -q .tmp\test_pkg_fix.py
setup
.teardown

1 passed in 0.01 seconds
```

Can you please provide a reproducible example?

**Comment by hayleyday** [comment]
@nicoddemus It appears that the issue I reported is invalid and that this is not the actual issue I am experiencing. My apologies for that. I might need some clarification on the intent/design of the package scope. Here is an explanation of the issue I am experiencing:

If I have multiple packages in my full overall test package, say test_foo; test_bar; test_baz, each with their own conftest.py and test modules, the tests execute in this order when I run the full overall test package:

1. test_bar package - setup code, asserts for bar modules
2. test_baz package - setup code, asserts for baz modules
3. test_foo package - setup code, asserts for foo modules
4. foo package teardown code
5. baz package teardown code
6. bar package teardown code

See attached screenshot. Please advise if this is intended behavior. Thank you very much for your time!

<img width="1476" alt="pytest_issue_3796" src="https://user-images.githubusercontent.com/30627825/44122093-fd41a680-9fe7-11e8-8746-cc4d1793baec.png">

**Comment by nicoddemus** [comment]
Hi @hayleyday sorry for the delay.

Hmm I would expect the tear down of the packages to occur right after the last test of the module inside of the package to finish. It is late now and I need to go to bed, but I will ping @jonozzz in case he has any comments. 👍

**Comment by akumarpatel** [comment]
> @nicoddemus It appears that the issue I reported is invalid and that this is not the actual issue I am experiencing. My apologies for that. I might need some clarification on the intent/design of the package scope. Here is an explanation of the issue I am experiencing:
> 
> If I have multiple packages in my full overall test package, say test_foo; test_bar; test_baz, each with their own conftest.py and test modules, the tests execute in this order when I run the full overall test package:
> 
> 1. test_bar package - setup code, asserts for bar modules
> 2. test_baz package - setup code, asserts for baz modules
> 3. test_foo package - setup code, asserts for foo modules
> 4. foo package teardown code
> 5. baz package teardown code
> 6. bar package teardown code
> 
> See attached screenshot. Please advise if this is intended behavior. Thank you very much for your time!
> 
> <img alt="pytest_issue_3796" width="1476" src="https://user-images.githubusercontent.com/30627825/44122093-fd41a680-9fe7-11e8-8746-cc4d1793baec.png">

@hayleyday Is your issue been resolved ? because I facing the same issue with teardown of package scope fixtures with pytest version 3.9.0.

**Comment by hayleyday** [comment]
@akumarpatel Sorry for the delay. My issue has been resolved... However, I have only been using pytest 3.7.3. If I find the time, I will upgrade to 3.9.0 and see if that changes anything for me.

**Comment by thenx** [comment]
Guess the bug is still there.

Env:
```
─➤  pip list 
Package             Version                   Editable project location
------------------- ------------------------- ----------------------------
attrs               22.2.0
exceptiongroup      1.1.0
iniconfig           2.0.0
packaging           23.0
pip                 22.3.1
pluggy              1.0.0
pytest              7.2.1
pytest-asyncio      0.20.3
setuptools          67.0.0
tomli               2.0.1
wheel               0.38.4

```



Folder structure:
```
─➤  tree tests                
tests
├── __init__.py
├── example
│   ├── __init__.py
│   ├── conftest.py
│   └── inner
│       ├── __init__.py
│       └── test_inner.py
└── outer
    ├── __init__.py
    └── test_outer.py

```

Content of `conftest.py`:
```python
import asyncio
from collections.abc import AsyncIterator, Iterable

import pytest


@pytest.fixture(scope="package")
def event_loop() -> Iterable[asyncio.AbstractEventLoop]:
    policy = asyncio.get_event_loop_policy()
    loop = policy.new_event_loop()
    yield loop
    loop.close()


@pytest.fixture(scope="package")
async def async_package_fixture() -> AsyncIterator[None]:
    yield

```

Content of `test_inner.py`:
```python
async def test_inner(async_package_fixture: None) -> None:
    pass

```

Content of `test_outer.py`:
```python
async def test_outer() -> None:
    pass

```

Output of `pytest --setup-show`:
```
─➤  pytest --setup-show
=============================================================================== test session starts ===============================================================================
platform darwin -- Python 3.10.9, pytest-7.2.1, pluggy-1.0.0
rootdir: <rootdir>, configfile: pyproject.toml, testpaths: tests
plugins: asyncio-0.20.3
asyncio: mode=auto
collected 2 items                                                                                                                                                                 

tests/example/inner/test_inner.py 
  SETUP    P event_loop
  SETUP    P async_package_fixture (fixtures used: event_loop)
        tests/example/inner/test_inner.py::test_inner (fixtures used: async_package_fixture, event_loop, request).
tests/outer/test_outer.py 
        SETUP    F event_loop
        tests/outer/test_outer.py::test_outer (fixtures used: event_loop).
        TEARDOWN F event_loop
  TEARDOWN P async_package_fixture
  TEARDOWN P event_loopE

===================================================================================== ERRORS ======================================================================================
_________________________________________________________________________ ERROR at teardown of test_outer _________________________________________________________________________

    def finalizer() -> None:
        """Yield again, to finalize."""
    
        async def async_finalizer() -> None:
            try:
                await gen_obj.__anext__()
            except StopAsyncIteration:
                pass
            else:
                msg = "Async generator fixture didn't stop."
                msg += "Yield only once."
                raise ValueError(msg)
    
>       event_loop.run_until_complete(async_finalizer())

.venv/lib/python3.10/site-packages/pytest_asyncio/plugin.py:297: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
../../.pyenv/versions/3.10.9/lib/python3.10/asyncio/base_events.py:624: in run_until_complete
    self._check_closed()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <_UnixSelectorEventLoop running=False closed=True debug=False>

    def _check_closed(self):
        if self._closed:
>           raise RuntimeError('Event loop is closed')
E           RuntimeError: Event loop is closed

../../.pyenv/versions/3.10.9/lib/python3.10/asyncio/base_events.py:515: RuntimeError
============================================================================= short test summary info =============================================================================
ERROR tests/outer/test_outer.py::test_outer - RuntimeError: Event loop is closed
=========================================================================== 2 passed, 1 error in 0.06s ============================================================================
sys:1: RuntimeWarning: coroutine '_wrap_asyncgen_fixture.<locals>._asyncgen_fixture_wrapper.<locals>.finalizer.<locals>.async_finalizer' was never awaited
RuntimeWarning: Enable tracemalloc to get the object allocation traceback

```

Guess the main info is the following:
```
tests/example/inner/test_inner.py 
  SETUP    P event_loop
  SETUP    P async_package_fixture (fixtures used: event_loop)
        tests/example/inner/test_inner.py::test_inner (fixtures used: async_package_fixture, event_loop, request).
tests/outer/test_outer.py 
        SETUP    F event_loop
        tests/outer/test_outer.py::test_outer (fixtures used: event_loop).
        TEARDOWN F event_loop
  TEARDOWN P async_package_fixture
  TEARDOWN P event_loopE
```

**Comment by aliaksandr-klimovich** [comment]
I faced same issue in pytest v7.2.0.
The teardown of the fixtures with the "package" scope is executed at the end of all tests.
![image](https://user-images.githubusercontent.com/7364160/221533408-28616f39-05d0-47a3-b83f-848d9d0969a3.png)
