### ISSUE TITLE
FileExistsError: [Errno 17] File exists: '/tmp/pytest-of-jenkins/pytest-0/.lock'

### ISSUE THREAD

**Issue by zzzeek** [pytest-dev/pytest#4181]
Hi there -

Just need to know what's happening on this one, this seems to be new code in py.test in version 3.9.1, my other build server running 3.8.2 doesn't have this issue.

is there....some kind of revolving numeric scheme such that more than one runner (I'm using pytest-xdist, 1.23.2 on both environments) is conflicting on this?   

this is SQLAlchemy's test suite running on jenkins.    

stack trace:
```

INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/home/jenkins/workspace/sqlalchemy_gerrit/b3d9d1a2/.tox/py37-cext-sqlite-postgresql/lib/python3.7/site-packages/_pytest/pathlib.py", line 127, in create_cleanup_lock
INTERNALERROR>     fd = os.open(str(lock_path), os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o644)
INTERNALERROR> FileExistsError: [Errno 17] File exists: '/tmp/pytest-of-jenkins/pytest-0/.lock'
INTERNALERROR> 
INTERNALERROR> The above exception was the direct cause of the following exception:
INTERNALERROR> 
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/home/jenkins/workspace/sqlalchemy_gerrit/b3d9d1a2/.tox/py37-cext-sqlite-postgresql/lib/python3.7/site-packages/_pytest/main.py", line 179, in wrap_session
INTERNALERROR>     config.hook.pytest_sessionstart(session=session)
INTERNALERROR>   File "/home/jenkins/workspace/sqlalchemy_gerrit/b3d9d1a2/.tox/py37-cext-sqlite-postgresql/lib/python3.7/site-packages/pluggy/hooks.py", line 284, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/home/jenkins/workspace/sqlalchemy_gerrit/b3d9d1a2/.tox/py37-cext-sqlite-postgresql/lib/python3.7/site-packages/pluggy/manager.py", line 67, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/home/jenkins/workspace/sqlalchemy_gerrit/b3d9d1a2/.tox/py37-cext-sqlite-postgresql/lib/python3.7/site-packages/pluggy/manager.py", line 61, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "/home/jenkins/workspace/sqlalchemy_gerrit/b3d9d1a2/.tox/py37-cext-sqlite-postgresql/lib/python3.7/site-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/home/jenkins/workspace/sqlalchemy_gerrit/b3d9d1a2/.tox/py37-cext-sqlite-postgresql/lib/python3.7/site-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/home/jenkins/workspace/sqlalchemy_gerrit/b3d9d1a2/.tox/py37-cext-sqlite-postgresql/lib/python3.7/site-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/home/jenkins/workspace/sqlalchemy_gerrit/b3d9d1a2/.tox/py37-cext-sqlite-postgresql/lib/python3.7/site-packages/xdist/dsession.py", line 81, in pytest_sessionstart
INTERNALERROR>     nodes = self.nodemanager.setup_nodes(putevent=self.queue.put)
INTERNALERROR>   File "/home/jenkins/workspace/sqlalchemy_gerrit/b3d9d1a2/.tox/py37-cext-sqlite-postgresql/lib/python3.7/site-packages/xdist/workermanage.py", line 67, in setup_nodes
INTERNALERROR>     nodes.append(self.setup_node(spec, putevent))
INTERNALERROR>   File "/home/jenkins/workspace/sqlalchemy_gerrit/b3d9d1a2/.tox/py37-cext-sqlite-postgresql/lib/python3.7/site-packages/xdist/workermanage.py", line 76, in setup_node
INTERNALERROR>     node.setup()
INTERNALERROR>   File "/home/jenkins/workspace/sqlalchemy_gerrit/b3d9d1a2/.tox/py37-cext-sqlite-postgresql/lib/python3.7/site-packages/xdist/workermanage.py", line 242, in setup
INTERNALERROR>     basetemp = self.config._tmpdirhandler.getbasetemp()
INTERNALERROR>   File "/home/jenkins/workspace/sqlalchemy_gerrit/b3d9d1a2/.tox/py37-cext-sqlite-postgresql/lib/python3.7/site-packages/_pytest/tmpdir.py", line 107, in getbasetemp
INTERNALERROR>     return py.path.local(self._tmppath_factory.getbasetemp().resolve())
INTERNALERROR>   File "/home/jenkins/workspace/sqlalchemy_gerrit/b3d9d1a2/.tox/py37-cext-sqlite-postgresql/lib/python3.7/site-packages/_pytest/tmpdir.py", line 66, in getbasetemp
INTERNALERROR>     prefix="pytest-", root=rootdir, keep=3, lock_timeout=LOCK_TIMEOUT
INTERNALERROR>   File "/home/jenkins/workspace/sqlalchemy_gerrit/b3d9d1a2/.tox/py37-cext-sqlite-postgresql/lib/python3.7/site-packages/_pytest/pathlib.py", line 235, in make_numbered_dir_with_cleanup
INTERNALERROR>     consider_lock_dead_if_created_before=consider_lock_dead_if_created_before,
INTERNALERROR>   File "/home/jenkins/workspace/sqlalchemy_gerrit/b3d9d1a2/.tox/py37-cext-sqlite-postgresql/lib/python3.7/site-packages/_pytest/pathlib.py", line 214, in cleanup_numbered_dir
INTERNALERROR>     try_cleanup(path, consider_lock_dead_if_created_before)
INTERNALERROR>   File "/home/jenkins/workspace/sqlalchemy_gerrit/b3d9d1a2/.tox/py37-cext-sqlite-postgresql/lib/python3.7/site-packages/_pytest/pathlib.py", line 196, in try_cleanup
INTERNALERROR>     delete_a_numbered_dir(path)
INTERNALERROR>   File "/home/jenkins/workspace/sqlalchemy_gerrit/b3d9d1a2/.tox/py37-cext-sqlite-postgresql/lib/python3.7/site-packages/_pytest/pathlib.py", line 166, in delete_a_numbered_dir
INTERNALERROR>     create_cleanup_lock(path)
INTERNALERROR>   File "/home/jenkins/workspace/sqlalchemy_gerrit/b3d9d1a2/.tox/py37-cext-sqlite-postgresql/lib/python3.7/site-packages/_pytest/pathlib.py", line 131, in create_cleanup_lock
INTERNALERROR>     EnvironmentError("cannot create lockfile in {path}".format(path=p)), e
INTERNALERROR>   File "<string>", line 3, in raise_from
INTERNALERROR> OSError: cannot create lockfile in /tmp/pytest-of-jenkins/pytest-0
/home/jenkins/workspace/sqlalchemy_gerrit/b3d9d1a2/.tox/py37-cext-sqlite-postgresql/lib/python3.7/site-packages/psycopg2
```

**Comment by nicoddemus** [comment]
Thanks @zzzeek for the report!

It is likely to be related to the new `pathlib.Path` implementation for creating temporary directories. 

cc @RonnyPfannschmidt

**Comment by RonnyPfannschmidt** [comment]
indeed there seems to be a conflict i'll try to come up with a test for the situation

**Comment by otrejoso** [comment]
I have the same issue happening in both Mac and Windows. Pretty much the backtrace for mac is the same on as @zzzeek pointed out, but in windows it has different backtrace. This started to happen as soon as I got pytest 3.9.1.
`INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "C:\src\ptiinstaller0\venv\lib\site-packages\_pytest\main.py", line 177, in wrap_session
INTERNALERROR>     config._do_configure()
INTERNALERROR>   File "C:\src\ptiinstaller0\venv\lib\site-packages\_pytest\config\__init__.py", line 610, in _do_configure
INTERNALERROR>     self.hook.pytest_configure.call_historic(kwargs=dict(config=self))
INTERNALERROR>   File "C:\src\ptiinstaller0\venv\lib\site-packages\pluggy\hooks.py", line 306, in call_historic
INTERNALERROR>     res = self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "C:\src\ptiinstaller0\venv\lib\site-packages\pluggy\manager.py", line 67, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "C:\src\ptiinstaller0\venv\lib\site-packages\pluggy\manager.py", line 61, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "C:\src\ptiinstaller0\venv\lib\site-packages\pluggy\callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "C:\src\ptiinstaller0\venv\lib\site-packages\pluggy\callers.py", line 81, in get_result
INTERNALERROR>     _reraise(*ex)  # noqa
INTERNALERROR>   File "C:\src\ptiinstaller0\venv\lib\site-packages\pluggy\callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "C:\src\ptiinstaller0\venv\lib\site-packages\testdriver\plugin.py", line 151, in pytest_configure
INTERNALERROR>     base_tmp_dir = str(config._tmpdirhandler.getbasetemp())
INTERNALERROR>   File "C:\src\ptiinstaller0\venv\lib\site-packages\_pytest\tmpdir.py", line 107, in getbasetemp
INTERNALERROR>     return py.path.local(self._tmppath_factory.getbasetemp().resolve())
INTERNALERROR>   File "C:\src\ptiinstaller0\venv\lib\site-packages\_pytest\tmpdir.py", line 66, in getbasetemp
INTERNALERROR>     prefix="pytest-", root=rootdir, keep=3, lock_timeout=LOCK_TIMEOUT
INTERNALERROR>   File "C:\src\ptiinstaller0\venv\lib\site-packages\_pytest\pathlib.py", line 235, in make_numbered_dir_with_cleanup
INTERNALERROR>     consider_lock_dead_if_created_before=consider_lock_dead_if_created_before,
INTERNALERROR>   File "C:\src\ptiinstaller0\venv\lib\site-packages\_pytest\pathlib.py", line 216, in cleanup_numbered_dir
INTERNALERROR>     try_cleanup(path, consider_lock_dead_if_created_before)
INTERNALERROR>   File "C:\src\ptiinstaller0\venv\lib\site-packages\_pytest\pathlib.py", line 196, in try_cleanup
INTERNALERROR>     delete_a_numbered_dir(path)
INTERNALERROR>   File "C:\src\ptiinstaller0\venv\lib\site-packages\_pytest\pathlib.py", line 170, in delete_a_numbered_dir
INTERNALERROR>     path.rename(garbage)
INTERNALERROR>   File "C:\src\ptiinstaller0\venv\lib\site-packages\pathlib2\__init__.py", line 1518, in rename
INTERNALERROR>     self._accessor.rename(self, target)
INTERNALERROR>   File "C:\src\ptiinstaller0\venv\lib\site-packages\pathlib2\__init__.py", line 547, in wrapped
INTERNALERROR>     return strfunc(str(pathobjA), str(pathobjB), *args)
INTERNALERROR> WindowsError: [Error 5] Access is denied`

**Comment by RonnyPfannschmidt** [comment]
@obestwalter the symlink target is negligible - please take a look if my open or fixes the issue in part

i believe part of the issue you are seeing is trying to break `py.path.make_numbered_dir` based locks with behave different in different platforms - it may require more sophisticated lock breaking

**Comment by obestwalter** [comment]
@RonnyPfannschmidt, I reckon you mean this one: https://github.com/RonnyPfannschmidt/pytest/tree/pathlib-fixes

Will try this tomorrow.

**Comment by RonnyPfannschmidt** [comment]
correct

**Comment by nicoddemus** [comment]
Fixed by https://github.com/pytest-dev/pytest/pull/4222

**Comment by otrejoso** [comment]
I am still having the same issue in windows running 3.9.3. Unless, the windows issue is totally different cause?
`INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "C:\src\ptiinstaller0\venv\lib\site-packages\_pytest\main.py", line 180, in wrap_session
INTERNALERROR>     config._do_configure()
INTERNALERROR>   File "C:\src\ptiinstaller0\venv\lib\site-packages\_pytest\config\__init__.py", line 617, in _do_configure
INTERNALERROR>     self.hook.pytest_configure.call_historic(kwargs=dict(config=self))
INTERNALERROR>   File "C:\src\ptiinstaller0\venv\lib\site-packages\pluggy\hooks.py", line 306, in call_historic
INTERNALERROR>     res = self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "C:\src\ptiinstaller0\venv\lib\site-packages\pluggy\manager.py", line 67, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "C:\src\ptiinstaller0\venv\lib\site-packages\pluggy\manager.py", line 61, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "C:\src\ptiinstaller0\venv\lib\site-packages\pluggy\callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "C:\src\ptiinstaller0\venv\lib\site-packages\pluggy\callers.py", line 81, in get_result
INTERNALERROR>     _reraise(*ex)  # noqa
INTERNALERROR>   File "C:\src\ptiinstaller0\venv\lib\site-packages\pluggy\callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "C:\src\ptiinstaller0\venv\lib\site-packages\testdriver\plugin.py", line 151, in pytest_configure
INTERNALERROR>     base_tmp_dir = str(config._tmpdirhandler.getbasetemp())
INTERNALERROR>   File "C:\src\ptiinstaller0\venv\lib\site-packages\_pytest\tmpdir.py", line 108, in getbasetemp
INTERNALERROR>     return py.path.local(self._tmppath_factory.getbasetemp().resolve())
INTERNALERROR>   File "C:\src\ptiinstaller0\venv\lib\site-packages\_pytest\tmpdir.py", line 67, in getbasetemp
INTERNALERROR>     prefix="pytest-", root=rootdir, keep=3, lock_timeout=LOCK_TIMEOUT
INTERNALERROR>   File "C:\src\ptiinstaller0\venv\lib\site-packages\_pytest\pathlib.py", line 265, in make_numbered_dir_with_cleanup
INTERNALERROR>     consider_lock_dead_if_created_before=consider_lock_dead_if_created_before,
INTERNALERROR>   File "C:\src\ptiinstaller0\venv\lib\site-packages\_pytest\pathlib.py", line 246, in cleanup_numbered_dir
INTERNALERROR>     try_cleanup(path, consider_lock_dead_if_created_before)
INTERNALERROR>   File "C:\src\ptiinstaller0\venv\lib\site-packages\_pytest\pathlib.py", line 226, in try_cleanup
INTERNALERROR>     maybe_delete_a_numbered_dir(path)
INTERNALERROR>   File "C:\src\ptiinstaller0\venv\lib\site-packages\_pytest\pathlib.py", line 200, in maybe_delete_a_numbered_dir
INTERNALERROR>     path.rename(garbage)
INTERNALERROR>   File "C:\src\ptiinstaller0\venv\lib\site-packages\pathlib2\__init__.py", line 1518, in rename
INTERNALERROR>     self._accessor.rename(self, target)
INTERNALERROR>   File "C:\src\ptiinstaller0\venv\lib\site-packages\pathlib2\__init__.py", line 547, in wrapped
INTERNALERROR>     return strfunc(str(pathobjA), str(pathobjB), *args)
INTERNALERROR> WindowsError: [Error 5] Access is denied`

**Comment by nicoddemus** [comment]
@otrejoso is definitely related, but is blowing up in a different place now it seems. Could you please open a new issue? Thanks!

**Comment by otrejoso** [comment]
@nicoddemus Issued filed. https://github.com/pytest-dev/pytest/issues/4262 Thanks.

**Comment by obestwalter** [comment]
Thanks @nicoddemus! Sorry for not following up on this - I wasn't able to provoke the race condition on my first tries and now wanted to try some ways to provoke it, but life got in the way.

**Comment by nicoddemus** [comment]
@obestwalter no worries! Hopefully things are sorted out now. 👍

**Comment by demartinofra** [comment]
I think there are still some edge cases where this is not handled correctly. I am running a series of concurrent pytest processes and was able to reproduce the issue. Here is the stack trace:

```
============================= test session starts ==============================
platform linux -- Python 3.7.2, pytest-4.6.3, py-1.8.0, pluggy-0.12.0 -- /usr/local/bin/.pyenv/versions/integration-tests/bin/python
cachedir: .pytest_cache
metadata: {'Python': '3.7.2', 'Platform': 'Linux-4.14.77-70.59.amzn1.x86_64-x86_64-with-debian-9.8', 'Packages': {'pytest': '4.6.3', 'py': '1.8.0', 'pluggy': '0.12.0'}, 'Plugins': {'html': '1.20.0', 'metadata': '1.8.0', 'xdist': '1.29.0', 'forked': '1.0.2', 'datadir': '1.3.0', 'sugar': '0.9.2', 'rerunfailures': '7.0'}, 'BUILD_NUMBER': '189', 'BUILD_ID': '189', 'BUILD_URL': 'https://parallelcluster-jenkins-commercial.aka.corp.amazon.com/job/integration_tests/189/', 'NODE_NAME': 'master', 'JOB_NAME': 'integration_tests', 'BUILD_TAG': 'jenkins-integration_tests-189', 'EXECUTOR_NUMBER': '15', 'JENKINS_URL': 'https://parallelcluster-jenkins-commercial.aka.corp.amazon.com/', 'JAVA_HOME': '/docker-java-home', 'WORKSPACE': '/var/jenkins_home/workspace/integration_tests'}
rootdir: /var/jenkins_home/workspace/integration_tests/pcluster/tests/integration-tests/tests
plugins: html-1.20.0, metadata-1.8.0, xdist-1.29.0, forked-1.0.2, datadir-1.3.0, sugar-0.9.2, rerunfailures-7.0
gw0 I / gw1 I / gw2 I / gw3 I / gw4 I / gw5 I / gw6 I / gw7 I

[gw0] linux Python 3.7.2 cwd: /var/jenkins_home/workspace/integration_tests/pcluster/tests/integration-tests
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/usr/local/bin/.pyenv/versions/integration-tests/lib/python3.7/site-packages/_pytest/main.py", line 204, in wrap_session
INTERNALERROR>     config.hook.pytest_sessionstart(session=session)
INTERNALERROR>   File "/usr/local/bin/.pyenv/versions/integration-tests/lib/python3.7/site-packages/pluggy/hooks.py", line 289, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/usr/local/bin/.pyenv/versions/integration-tests/lib/python3.7/site-packages/pluggy/manager.py", line 87, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/usr/local/bin/.pyenv/versions/integration-tests/lib/python3.7/site-packages/pluggy/manager.py", line 81, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "/usr/local/bin/.pyenv/versions/integration-tests/lib/python3.7/site-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/usr/local/bin/.pyenv/versions/integration-tests/lib/python3.7/site-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/usr/local/bin/.pyenv/versions/integration-tests/lib/python3.7/site-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/usr/local/bin/.pyenv/versions/integration-tests/lib/python3.7/site-packages/xdist/dsession.py", line 81, in pytest_sessionstart
INTERNALERROR>     nodes = self.nodemanager.setup_nodes(putevent=self.queue.put)
INTERNALERROR>   File "/usr/local/bin/.pyenv/versions/integration-tests/lib/python3.7/site-packages/xdist/workermanage.py", line 64, in setup_nodes
INTERNALERROR>     nodes.append(self.setup_node(spec, putevent))
INTERNALERROR>   File "/usr/local/bin/.pyenv/versions/integration-tests/lib/python3.7/site-packages/xdist/workermanage.py", line 73, in setup_node
INTERNALERROR>     node.setup()
INTERNALERROR>   File "/usr/local/bin/.pyenv/versions/integration-tests/lib/python3.7/site-packages/xdist/workermanage.py", line 246, in setup
INTERNALERROR>     basetemp = self.config._tmpdirhandler.getbasetemp()
INTERNALERROR>   File "/usr/local/bin/.pyenv/versions/integration-tests/lib/python3.7/site-packages/_pytest/tmpdir.py", line 118, in getbasetemp
INTERNALERROR>     return py.path.local(self._tmppath_factory.getbasetemp().resolve())
INTERNALERROR>   File "/usr/local/bin/.pyenv/versions/integration-tests/lib/python3.7/site-packages/_pytest/tmpdir.py", line 79, in getbasetemp
INTERNALERROR>     prefix="pytest-", root=rootdir, keep=3, lock_timeout=LOCK_TIMEOUT
INTERNALERROR>   File "/usr/local/bin/.pyenv/versions/integration-tests/lib/python3.7/site-packages/_pytest/pathlib.py", line 267, in make_numbered_dir_with_cleanup
INTERNALERROR>     consider_lock_dead_if_created_before=consider_lock_dead_if_created_before,
INTERNALERROR>   File "/usr/local/bin/.pyenv/versions/integration-tests/lib/python3.7/site-packages/_pytest/pathlib.py", line 246, in cleanup_numbered_dir
INTERNALERROR>     try_cleanup(path, consider_lock_dead_if_created_before)
INTERNALERROR>   File "/usr/local/bin/.pyenv/versions/integration-tests/lib/python3.7/site-packages/_pytest/pathlib.py", line 227, in try_cleanup
INTERNALERROR>     if ensure_deletable(path, consider_lock_dead_if_created_before):
INTERNALERROR>   File "/usr/local/bin/.pyenv/versions/integration-tests/lib/python3.7/site-packages/_pytest/pathlib.py", line 219, in ensure_deletable
INTERNALERROR>     lock.unlink()
INTERNALERROR>   File "/usr/local/bin/.pyenv/versions/3.7.2/lib/python3.7/pathlib.py", line 1277, in unlink
INTERNALERROR>     self._accessor.unlink(self)
INTERNALERROR> FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pytest-of-jenkins/pytest-1681/.lock'
```

A potential mitigation to this problem might be to generate the numbered dir with a random suffix rather than a sequential one, unless some code depends on this logic: https://github.com/pytest-dev/pytest/blob/4.6.3/src/_pytest/pathlib.py#L123
